### PR TITLE
Python 3.6.6

### PR DESCRIPTION
**Pull request by dersteppenwolf**
The tool only worked with Python 3.6.6 (from Arcgis Pro 2.3.3)

### CODE REVIEW

**Comment by AlexArcPy** [comment]
Hi there, thanks for reaching out. The `registrant` is operable on both Python 2.7 (used with ArcGIS Desktop) and Python 3.x (used with ArcGIS Pro). So, removing 2.7 wouldn't be right. Are you experiencing issues using 2.7 or you only use 3.6 with Pro?

Also, I am not keen to include some Windows libraries as the requirements as it is not really a requirement for the package to operate but rather something `numpy` relies on and the user will figure this out along the way.

Does this make sense?

**Comment by dersteppenwolf** [comment]
Hi, 
I tried to using using python 2.7 from Arcgis Desktop 10.6.1 but it didn't work due to numpy problems.
During installation the program required that library from MS.

Btw, nice work!

**Comment by AlexArcPy** [comment]
> 
> 
> Hi,
> I tried to using using python 2.7 from Arcgis Desktop 10.6.1 but it didn't work due to numpy problems.
> During installation the program required that library from MS.
> 
> Btw, nice work!

Me and many other users are able to use 2.7 version of Python with ArcGIS Desktop, but I have seen that some people experienced `numpy` related issues. Well, there always be such issues and there is not much one can do about it.

Glad you like the tool.

I don't think changing the requirements would be useful, but wrapping `get_attachments_count` into a try-catch could be helpful. Could you please elaborate more on what type of exception was thrown and under what condition? I am genuinely curious.

**Comment by dersteppenwolf** [comment]
Hi, this is the exception: "numpy.dtype has the wrong size, try recompiling. Expected 52, got 56"

> C:\Python27\ArcGIS10.6\python ExportHtmlReportForFGDB.py
Traceback (most recent call last):
  File "ExportHtmlReportForFGDB.py", line 5, in <module>
    import registrant
  File "C:\Python27\ArcGIS10.6\lib\site-packages\registrant-0.7-py2.7.egg\registrant\__init__.py", line 4, in <module>
    from registrant._reporter import Reporter  # noqa: F401
  File "C:\Python27\ArcGIS10.6\lib\site-packages\registrant-0.7-py2.7.egg\registrant\_reporter.py", line 12, in <module>
    import pandas as pd
  File "C:\Python27\ArcGIS10.6\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Python27\ArcGIS10.6\lib\site-packages\pandas\_libs\__init__.py", line 3, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas\_libs\src\numpy.pxd", line 157, in init pandas._libs.tslib (pandas\_libs\tslib.c:117317)
ValueError: numpy.dtype has the wrong size, try recompiling. Expected 52, got 56


Also, I had to add a "try catch" to handle an error of one of my fgdbs:
https://github.com/AlexArcPy/registrant/compare/master...dersteppenwolf:master#diff-c33fdb2f6f5953fde076f6c0c29bae9b

Best

**Pull request closed without merging**
